[[plugins]]
repo = '/usr/local/opt/fzf'
if = 'g:is_mac && isdirectory("/usr/local/opt/fzf")'

[[plugins]]
repo = 'junegunn/fzf'
if = '!g:is_mac'
build = './install --bin'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'jreybert/vimagit'
on_cmd = 'Magit'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
rev = '54d889a63716ee2f1818aa2ec5082db47147147b'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'junegunn/vim-easy-align'

# [[plugins]]
# repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'brooth/far.vim'
on_cmd = [ 'Far', 'Farp', 'F' ]

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repo = 'matze/vim-move'

[[plugins]]
repo = 'dhruvasagar/vim-open-url'
rev = '595f964eca353f6cc158f953d879dda55e45370b'

[[plugins]]
repo = 'jpalardy/vim-slime'
rev = 'cf896c1f4f37a9feb15d657dfd120aeeb6215ad8'

# [[plugins]]
# repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'w0rp/ale'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# # on_event = 'InsertEnter'
# hook_post_update = ':UpdateRemotePlugins'
# # hook_source = 'call deoplete#enable()'

# [[plugins]]
# repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'carlosrocha/vim-flow-plus'
rev = '458cc22cc4adb9106f23839df97e13557ec7444c'
on_ft = 'javascript'

[[plugins]]
repo = 'rgrinberg/vim-ocaml'
on_ft = [ 'ocaml', 'dune', 'opam', 'oasis', 'ocamlbuild_tags', 'sexplib' ]

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = [ 'javascript', 'jsx', 'javascript.jsx' ]

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'derekelkins/agda-vim'
on_ft = 'agda'

[[plugins]]
repo = 'srcery-colors/srcery-vim'
rev = '2aaba124461dacd1089dda0c622197f849a685f2'
