# vim: foldmethod=marker

[[plugins]]
repo = '/usr/local/opt/fzf'
if = 'g:is_mac && isdirectory("/usr/local/opt/fzf")'

[[plugins]]
repo = 'junegunn/fzf'
if = '!g:is_mac'
build = './install --bin'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'

# TODO: vim-clap?

# [[plugins]]
# repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'tommcdo/vim-exchange'

[[plugins]]
repo = 't9md/vim-choosewin'

[[plugins]]
repo = 'matze/vim-move'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'chaoren/vim-wordmotion'

[[plugins]]
repo = 'dhruvasagar/vim-open-url'
rev = '595f964eca353f6cc158f953d879dda55e45370b'

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'voldikss/vim-floaterm'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'jreybert/vimagit'
on_cmd = 'Magit'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# [[plugins]]
# repo = 'Shougo/defx.nvim'

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'tpope/vim-unimpaired'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# # on_event = 'InsertEnter'
# hook_post_update = ':UpdateRemotePlugins'
# # hook_source = 'call deoplete#enable()'

# [[plugins]]
# repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'jpalardy/vim-slime'
rev = 'cf896c1f4f37a9feb15d657dfd120aeeb6215ad8'

[[plugins]]
repo = 'brooth/far.vim'
on_cmd = [ 'Far', 'Farp', 'F' ]

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd = 'Goyo'

[[plugins]]
repo = 'chrisbra/Colorizer'

# Languages {{{

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = [
  \ 'javascript',
  \ 'ocaml',
  \ 'haskell'
  \ ]
'''

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'carlosrocha/vim-flow-plus'
on_cmd = [ 'FlowCoverageToggle' ]

[[plugins]]
repo = 'rgrinberg/vim-ocaml'
on_ft = [ 'ocaml', 'dune', 'opam', 'oasis', 'ocamlbuild_tags', 'sexplib' ]

[[plugins]]
repo = 'neovimhaskell/haskell-vim'

[[plugins]]
repo = 'derekelkins/agda-vim'

# }}}

# Themes {{{

[[plugins]]
repo = 'srcery-colors/srcery-vim'
rev = '2aaba124461dacd1089dda0c622197f849a685f2'

# }}}

# ^\s*#\@!.*[[plugins\]\]
